kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-storage
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo-storage/"
