apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "mongo-pv-claim"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "300Mi"
  volumeName: "mongo-storage"
