apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  type: NodePort
  ports:
    - port: 27017
      nodePort: 30000
      name: http
  selector:
    name: mongodb
    
